<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BitFuture</title>
</head>

<body>
    <div class="menu">
        <ul>
            <li><a href="#">I want to receive notification</a></li>
        </ul>
    </div>
    <div class="container">
        <div class="mayer">
            <?php
            echo "Mayer Multiple is : " . $mayer_multiple;
            ?>
        </div>
    </div>


</body>


</html>
<style>
    * {
        margin: 0;
        padding: 0;
    }

    .menu {
        display: flex;
        justify-content: flex-end;
        justify-items: center;
    }

    .menu li {
        padding: 7px;
        list-style-type: none;
        font-size: 20px;
    }

    .menu li a {
        text-decoration: none;
        color: black;
    }

    .container {
        display: flex;
        justify-content: center;
        justify-items: center;
    }

    .container .mayer {
        font-size: 60px;
        padding: 30px;
    }

    .mayer span {
        color: green;
    }
</style>